### ISSUE TITLE
I can't send commands to GrandMA2 onPC

### ISSUE THREAD

**Issue by Everton747** [tap-chris/mamsc#1]
I'm trying to use simple commands to trigger macros, but no transmitter command seems to be received by the onPC software. I read that the operation is different in grandMA 2. Should I change something in my code to work?

ps. The receiver works fine.

my code:
`
const msc = require('mamsc').out(6004);
`
`
msc.fire(1);
`

grandMA config:

![grandMA-Config](https://user-images.githubusercontent.com/13826833/57415481-5ed72000-71ca-11e9-9784-42099d69b502.png)

**Comment by tap-chris** [comment]
Everything you did looks fine to me.
I tested it with your settings and code on my side, onPC and node running on the same host. onPC is also running on the loop back interface. Worked right away.
Are you running node and onPC on the same host?
Can you try adding the address of the onPC host when creating the Transmitter (second parameter). For example if running on localhost:
`const msc = require('mamsc').out(6004, '127.0.0.1')`
This will force the Transmitter to send unicast messages. If this works, check which interface/address onPC is bound to.
By default a broadcast is send so it should technically arrive but this strongly depends on the network setup and settings.
Let me know what your setup is and we go from there.

**Comment by Everton747** [comment]
Thanks for the help help, now with '127.0.0.1' worked. I will soon test on two different computers.
